### ISSUE TITLE
Json Parsing Error during invalidating tokens

### ISSUE THREAD

**Issue by droidamar007** [microsoftgraph/microsoft-graph-docs#11421]
Hello Devs,

I'm trying to invalidate user's tokens using graph api as below - 

```
final HeaderOption headerOption = new HeaderOption("Content-Type", "application/json");
final List<Option> requestOptions = new LinkedList<>();
requestOptions.add(headerOption);
graphClient.users("user-id")
        .revokeSignInSessions()
        .buildRequest(requestOptions)
        .post();
```

SDK - `implementation 'com.microsoft.graph:microsoft-graph:2.5.0'`

> I've set .default scope for ClientCredentialProvider.

I'm getting below error - 

```
CoreHttpProvider[access$000] - 72Error during http request
Throwable detail: com.microsoft.graph.core.ClientException: Error during http request

com.microsoft.graph.core.ClientException: Error during http request
	at com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:471)
	at com.microsoft.graph.http.CoreHttpProvider.access$000(CoreHttpProvider.java:72)
	at com.microsoft.graph.http.CoreHttpProvider$1.run(CoreHttpProvider.java:171)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:836)
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a boolean but was BEGIN_OBJECT at line 1 column 2 path $
	at com.google.gson.Gson.fromJson(Gson.java:944)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at com.google.gson.Gson.fromJson(Gson.java:817)
	at com.microsoft.graph.serializer.DefaultSerializer.deserializeObject(DefaultSerializer.java:82)
	at com.microsoft.graph.http.CoreHttpProvider.handleJsonResponse(CoreHttpProvider.java:532)
	at com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:448)
	... 5 more
Caused by: java.lang.IllegalStateException: Expected a boolean but was BEGIN_OBJECT at line 1 column 2 path $
	at com.google.gson.stream.JsonReader.nextBoolean(JsonReader.java:854)
	at com.google.gson.internal.bind.TypeAdapters$3.read(TypeAdapters.java:144)
	at com.google.gson.internal.bind.TypeAdapters$3.read(TypeAdapters.java:133)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	... 11 more

```

I've provide the **User.ReadWrite.All, Directory.ReadWrite.All** permission but **Directory.AccessAsUser.All** permission is not listed in the portal.

-I'm stuck in it with 3 days so prompt help is appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4662c3f7-8566-09b3-962c-2cfcccfcfc2f
* Version Independent ID: 1cdc7db2-7c2c-9b23-16f7-05e76f588f6c
* Content: [user: revokeSignInSessions - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-revokesigninsessions?view=graph-rest-1.0&tabs=java)
* Content Source: [api-reference/v1.0/api/user-revokesigninsessions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-revokesigninsessions.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @krbain
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by nk6096** [comment]
I am also facing same issue, still not found any solution for this.

**Comment by droidamar007** [comment]
@krbain Any chance to get a reply on this thread? It has been more than a month and I'm still not able to proceed with this. What kind of support this is :(
