### ISSUE TITLE
Date format in notification is incorrect

### ISSUE THREAD

**Issue by vanta** [microsoftgraph/microsoft-graph-docs#1400]
When I handle notifications form subscription in Graph (for events) I receive following mapping error:
```
Thrown org.jboss.resteasy.spi.ReaderException with id: cd004d2d-fe7e-4915-b379-087da
13e0ef2: org.jboss.resteasy.spi.ReaderException: org.codehaus.jackson.map.JsonMappingException: Can not construct instance of java.ut
il.Date from String value '2017-06-11T12:23:21.88+00:00': not a valid representation (error: Can not parse date "2017-06-11T12:23:21.
88+00:00": not compatible with any of standard forms ("yyyy-MM-dd'T'HH:mm:ss.SSSZ", "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'", "EEE, dd MMM yyyy
 HH:mm:ss zzz", "yyyy-MM-dd"))
```

So date format in notification I receive is `2017-06-11T12:23:21.88+00:00` - note two-digit milliseconds. When they are 3, everything works fine. I can hack that but this is not aligned with ISO8601 format.
Please also note that expiration date format mentioned on documentation page (https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/resources/webhooks) is `"expirationDateTime":"\"2016-03-19T22:11:09.952Z\"",` which is consistent with date format in subscription entity.

Please align it or change the documentation so it states explicitly that date format does not follow ISO8601 format and what the format is with few examples (different timezones, millis, etc.).

**Comment by SomeshChandra-MSFT** [comment]
Thanks for reporting the issue. We will reply back with proposed solution shortly.

**Comment by vanta** [comment]
@SomeshChandra-MSFT Looking forward for seeing it, hacking unmarchall is not best way to express yourself as developer ;) Btw. I've already filled PR with adjustments to notifications page, it's slightly related: https://github.com/microsoftgraph/microsoft-graph-docs/pull/1347

**Comment by markdstafford** [comment]
Hi @vanta - @SomeshChandra-MSFT looped me into this issue. As far as I know, ISO 8601 does not stipulate a limitation on number of digits in fractional seconds. That said, it seems like more than three digits is a known issue with Java <8. (For what it's worth, it was also an issue with certain versions of Internet Explorer.) Have you tried using [joda-time](http://www.joda.org/joda-time/)'s [dateHourMinuteSecondFraction](http://joda-time.sourceforge.net/apidocs/org/joda/time/format/ISODateTimeFormat.html#dateHourMinuteSecondFraction())?

**Comment by vanta** [comment]
Hi @markdstafford, I don't have a problem with more then 3 digits in fraction. I have a problem when there is only 1 or2 digits. I use other library (see details below) but I checked the one you mentioned and it also fails to parse such date. I can see here https://en.wikipedia.org/wiki/ISO_8601#Times that it is:
```
hh:mm:ss.sss	or	hhmmss.sss
hh:mm:ss	or	hhmmss
hh:mm	or	hhmm
hh	
```
I use `org.codehaus.jackson.map.util.ISO8601Utils` class and when I use it to parse such date as `2017-06-17T23:59:59.11Z`it fails:

```
    @Test
    public void should(){
        final Date date = ISO8601Utils.parse("2017-06-17T23:59:59.11Z");
    }
```
ends up with:
```
java.lang.IllegalArgumentException: Failed to parse date 2017-06-17T23:59:59.11Z

	at org.codehaus.jackson.map.util.ISO8601Utils.parse(ISO8601Utils.java:159)
	at IsoTest.should(IsoTest.java:9)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.NumberFormatException: Invalid number: 2017-06-17T23:59:59.11Z
	at org.codehaus.jackson.map.util.ISO8601Utils.parseInt(ISO8601Utils.java:207)
	at org.codehaus.jackson.map.util.ISO8601Utils.parse(ISO8601Utils.java:127)
	... 23 more
```

**Comment by SomeshChandra-MSFT** [comment]
Hi @vanta The same wiki link has the following text 
"_There is no limit on the number of decimal places for the decimal fraction. However, the number of decimal places needs to be agreed to by the communicating parties_."

In this scenario, the communicating parties are the client creating the subscription and the client receiving the notifications. If the client receiving notification prefers 3 or more decimal places, then it can ensure that subscription creator specifies an expirationDateTime containing 3 or more decimal places.

Example, if you put  "expirationDateTime": "2017-06-30T19:15:16.2244Z" at subscription creation time, then you would receive the same at notification time. Or you could truncate and get rid of all decimal places at creation time. Microsoft graph would honor values provided during create and supply the same value at notification time.

Let us know if above appraoch works for you.

**Comment by jthake-msft** [comment]
Closed due to no response.
