### ISSUE TITLE
Microsoft.SkypeSpaces.MiddleTier.Common.ServiceException Exception when trying to add Microsoft Teams app using Microsoft Graph

### ISSUE THREAD

**Issue by RazmikGevorgyan** [microsoftgraph/microsoft-graph-docs#17523]
Microsoft.Graph.ServiceException
  HResult=0x80131500
  Message=Code: BadRequest
Message: Exception in CreateOrUpdateUserAppEntitlementAsync while sending app status update event to Chat Service for bot installation. UserId: '**', AppId: '**', ExternalId: '***', Exception: 'Microsoft.SkypeSpaces.MiddleTier.Common.ServiceException: Failed to execute Skype backend request CreateThreadRequest.
   at Microsoft.Skype.Chat.WebServices.Requests.ServiceRequestBase`1.<ExecuteHttpRequest>d__49.MoveNext() in D:\a\_work\1\s\Source\BackendServices\SkypeChatService\Requests\ServiceRequestBase.cs:line 630
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Skype.Chat.WebServices.Requests.ServiceRequestBase`1.<>c__DisplayClass34_0.<<Execute>b__0>d.MoveNext() in D:\a\_work\1\s\Source\BackendServices\SkypeChatService\Requests\ServiceRequestBase.cs:line 166
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Polly.Retry.AsyncRetryEngine.<ImplementationAsync>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Polly.AsyncPolicy`1.<ExecuteAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Skype.Chat.WebServices.Requests.ServiceRequestBase`1.<Execute>d__34.MoveNext() in D:\a\_work\1\s\Source\BackendServices\SkypeChatService\Requests\ServiceRequestBase.cs:line 162
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Skype.Chat.WebServices.SkypeChatService.<CreateChatServiceThreadOnBehalfOfAsync>d__133.MoveNext() in D:\a\_work\1\s\Source\BackendServices\SkypeChatService\SkypeChatService.cs:line 2242
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SkypeSpaces.MiddleTier.Provider.Utilities.ChatSkypeHelper.<Create1on1ConversationAsync>d__1.MoveNext() in D:\a\_work\1\s\Source\Provider\Provider\Utilities\ChatSkypeHelper.cs:line 94
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Polly.Retry.AsyncRetryEngine.<ImplementationAsync>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Polly.AsyncPolicy.<ExecuteAsync>d__21`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SkypeSpaces.MiddleTier.Common.Utilities.ServiceRequestRetryUtility.<ExecuteRequest>d__12`1.MoveNext() in D:\a\_work\1\s\Source\Common\Common\Utilities\ServiceRequestRetryUtility.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SkypeSpaces.MiddleTier.Common.Utilities.ServiceRequestRetryUtility.<ExecuteRequestWithRetryDelay>d__9`1.MoveNext() in D:\a\_work\1\s\Source\Common\Common\Utilities\ServiceRequestRetryUtility.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SkypeSpaces.MiddleTier.Provider.Apps.AppsProvider.<IssueAppInstallStateUpdationMessageTasksFor1on1Async>d__217.MoveNext() in D:\a\_work\1\s\Source\Provider\Provider\Apps\AppsProvider.cs:line 5431
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SkypeSpaces.MiddleTier.Provider.Apps.AppsProvider.<CreateOrUpdateUserAppEntitlementAsync>d__186.MoveNext() in D:\a\_work\1\s\Source\Provider\Provider\Apps\AppsProvider.cs:line 3039', userEntitlementEtag "Y2vqKwrZs1fRrS5lVAh0uw=="Failed to execute Skype backend request CreateThreadRequest.
Inner error:
	Code: BadRequest
Message: Exception in CreateOrUpdateUserAppEntitlementAsync while sending app status update event to Chat Service for bot installation. UserId: '176ff0a9-7656-40e5-a43b-cb470e33f219', AppId: '826d9f8f-877a-4198-a4e1-1761b6a724ff', ExternalId: 'eb9699c0-29c1-4706-bc51-42c1886ba639', Exception: 'Microsoft.SkypeSpaces.MiddleTier.Common.ServiceException: Failed to execute Skype backend request CreateThreadRequest.
   at Microsoft.Skype.Chat.WebServices.Requests.ServiceRequestBase`1.<ExecuteHttpRequest>d__49.MoveNext() in D:\a\_work\1\s\Source\BackendServices\SkypeChatService\Requests\ServiceRequestBase.cs:line 630
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Skype.Chat.WebServices.Requests.ServiceRequestBase`1.<>c__DisplayClass34_0.<<Execute>b__0>d.MoveNext() in D:\a\_work\1\s\Source\BackendServices\SkypeChatService\Requests\ServiceRequestBase.cs:line 166
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Polly.Retry.AsyncRetryEngine.<ImplementationAsync>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Polly.AsyncPolicy`1.<ExecuteAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Skype.Chat.WebServices.Requests.ServiceRequestBase`1.<Execute>d__34.MoveNext() in D:\a\_work\1\s\Source\BackendServices\SkypeChatService\Requests\ServiceRequestBase.cs:line 162
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Skype.Chat.WebServices.SkypeChatService.<CreateChatServiceThreadOnBehalfOfAsync>d__133.MoveNext() in D:\a\_work\1\s\Source\BackendServices\SkypeChatService\SkypeChatService.cs:line 2242
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SkypeSpaces.MiddleTier.Provider.Utilities.ChatSkypeHelper.<Create1on1ConversationAsync>d__1.MoveNext() in D:\a\_work\1\s\Source\Provider\Provider\Utilities\ChatSkypeHelper.cs:line 94
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Polly.Retry.AsyncRetryEngine.<ImplementationAsync>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Polly.AsyncPolicy.<ExecuteAsync>d__21`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SkypeSpaces.MiddleTier.Common.Utilities.ServiceRequestRetryUtility.<ExecuteRequest>d__12`1.MoveNext() in D:\a\_work\1\s\Source\Common\Common\Utilities\ServiceRequestRetryUtility.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SkypeSpaces.MiddleTier.Common.Utilities.ServiceRequestRetryUtility.<ExecuteRequestWithRetryDelay>d__9`1.MoveNext() in D:\a\_work\1\s\Source\Common\Common\Utilities\ServiceRequestRetryUtility.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SkypeSpaces.MiddleTier.Provider.Apps.AppsProvider.<IssueAppInstallStateUpdationMessageTasksFor1on1Async>d__217.MoveNext() in D:\a\_work\1\s\Source\Provider\Provider\Apps\AppsProvider.cs:line 5431
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SkypeSpaces.MiddleTier.Provider.Apps.AppsProvider.<CreateOrUpdateUserAppEntitlementAsync>d__186.MoveNext() in D:\a\_work\1\s\Source\Provider\Provider\Apps\AppsProvider.cs:line 3039', userEntitlementEtag "Y2vqKwrZs1fRrS5lVAh0uw=="Failed to execute Skype backend request CreateThreadRequest.
Inner error:
	AdditionalData:
	date: 2022-06-30T09:43:57
	request-id: 7a707ac0-1f3c-4c01-8b9b-999e43cc598e
	client-request-id: 7a707ac0-1f3c-4c01-8b9b-999e43cc598e
ClientRequestId: 7a707ac0-1f3c-4c01-8b9b-999e43cc598e

  Source=Microsoft.Graph.Core
  StackTrace:
   at Microsoft.Graph.HttpProvider.<SendAsync>d__18.MoveNext()
   at Microsoft.Graph.BaseRequest.<SendRequestAsync>d__40.MoveNext()
   at Microsoft.Graph.BaseRequest.<SendAsync>d__34`1.MoveNext()
   at DoworkAssistant.Bot.Models.ProactiveAppIntallationHelper.<AppinstallationforPersonal>d__2.MoveNext() in 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8bf2eb30-1ae8-4131-9b71-86946d9bd13f
* Version Independent ID: 875de937-5281-afe4-5db3-399e29becfec
* Content: [Install app for user - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/userteamwork-post-installedapps?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/userteamwork-post-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/userteamwork-post-installedapps.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @AkJo
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by AkJo** [comment]
Thank you for reporting this. The product team is investigating this now.

**Comment by RazmikGevorgyan** [comment]
The problem was the Teams app which was automatically generated by the Teams Toolkit Microsoft Graph was not recognized it as the Org app but it was, after creating the app 
manually and publishing it to the organization I was able to install it using the Graph script
